CREATE TABLE IF NOT EXISTS respuesta (
  ID_respuesta INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ID_ESTUDIANTE INTEGER NOT NULL,
  ID_PREGUNTA INTEGER NOT NULL,
  NUMERO_DE_INTENTO INTEGER NOT NULL,
  tiempo_respuesta FLOAT NOT NULL,
  FOREIGN KEY (ID_ESTUDIANTE) REFERENCES estudiante(ID_ESTUDIANTE),
  FOREIGN KEY (ID_PREGUNTA) REFERENCES pregunta(ID_PREGUNTA)
);

CREATE TABLE IF NOT EXISTS encargado_plantel (
  ID_ENCARGADO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ID_USUARIO INTEGER NOT NULL,
  ID_PLANTEL INTEGER NOT NULL,
  NUMERO_TELEFONO VARCHAR(10) NOT NULL,
  FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO),
  FOREIGN KEY (ID_PLANTEL) REFERENCES plantel(ID_PLANTEL)
);

CREATE TABLE IF NOT EXISTS estudiante (
  ID_ESTUDIANTE INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ID_USUARIO INTEGER NOT NULL,
  GENERO CHAR(1) NOT NULL,
  EDAD INTEGER NOT NULL,
  CONTEXTO VARCHAR(200) NOT NULL,
  TIPO_FAMILIA VARCHAR(50) NOT NULL,
  ID_GRUPO INTEGER NOT NULL,
  FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO),
  FOREIGN KEY (ID_GRUPO) REFERENCES grupo(ID_GRUPO)
);

CREATE TABLE IF NOT EXISTS grupo (
  ID_GRUPO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  GRADO INTEGER NOT NULL,
  LETRA CHAR(1) NOT NULL,
  ID_PLANTEL INTEGER NOT NULL,
  FOREIGN KEY (ID_PLANTEL) REFERENCES plantel(ID_PLANTEL)
);

CREATE TABLE IF NOT EXISTS plantel (
  ID_PLANTEL INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  NOMBRE_PLANTEL varchar(100) NOT NULL,
  DOMICILIO varchar(200) NOT NULL,
  NUMERO_TELEFONO varchar(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS pregunta (
  ID_PREGUNTA INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  PLANTEAMIENTO varchar(200) NOT NULL,
  ID_MODULO INTEGER NOT NULL,
  ID_FASE INTEGER NOT NULL,
  ID_MATERIAL_CONSULTA INTEGER, 
  FOREIGN KEY (ID_MATERIAL_CONSULTA) REFERENCES material_consulta(ID_MATERIAL_CONSULTA),
  FOREIGN KEY (ID_MODULO) REFERENCES modulo(ID_MODULO),
  FOREIGN KEY (ID_FASE) REFERENCES fase(ID_FASE)
); 

CREATE TABLE IF NOT EXISTS material_consulta(
  ID_MATERIAL_CONSULTA INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  TEXTO varchar(500) NOT NULL,
  NOMBRE varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS opcion (
  ID_OPCION INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ID_PREGUNTA INTEGER NOT NULL,
  INCISO varchar(1) NOT NULL,
  CORRECTA BOOLEAN NOT NULL,
  DESCRIPCION varchar(200) NOT NULL,
  FOREIGN KEY (ID_PREGUNTA) REFERENCES pregunta(ID_PREGUNTA)
); 

CREATE TABLE IF NOT EXISTS usuario (
  ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  NOMBRE_USUARIO varchar(50) NOT NULL,
  NOMBRE_COMPLETO varchar(100) NOT NULL,
  EMAIL varchar(50) NOT NULL,
  PASSWORD varchar(50) NOT NULL,
  TIPO_USUARIO varchar(1) NOT NULL
); 

CREATE TABLE IF NOT EXISTS modulo (
  ID_MODULO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  NOMBRE varchar(50) NOT NULL
); 

CREATE TABLE IF NOT EXISTS fase (
  ID_FASE INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  NOMBRE varchar(50) NOT NULL
); 



